### ISSUE TITLE
Referencing Rhino Assemblies on Mac Platform

### ISSUE THREAD

**Issue by vitadin** [mcneel/SimpleRhinoTests#2]
The current documentation and examples provided for referencing Rhino assemblies are primarily based on the Windows platform. There is a lack of guidance and examples for users working on the Mac platform. This creates challenges for Mac users like me who need to reference Rhino assemblies in their projects.

## Steps to Reproduce
I tried to update the [`SimpleNUnitTests.csproj`] (https://github.com/mcneel/SimpleRhinoTests/blob/main/SimpleUnitTests/SimpleNUnitTests.csproj) as following 

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net7.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <RhinoSystemDirectory>/Applications/Rhino 8.app/Contents/Frameworks/RhCore.framework/Versions/A/Resources/RhinoCommon.dll</RhinoSystemDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="NUnit" Version="3.*" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.*" />
    <PackageReference Include="Rhino.Testing" Version="8.0.16-beta" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.Contains('net7.0')) == 'true'">
    <Reference Include="$(RhinoSystemDirectory)" Private="False" />
  </ItemGroup>



  <ItemGroup>
    <None Update="Rhino.Testing.Configs.xml" CopyToOutputDirectory="always" />
    <None Update="Files\circle.3dm" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Files\circle.gh" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Files\point_error.gh" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>

```

and [`Rhino.Testing.Configs.xml`](https://github.com/mcneel/SimpleRhinoTests/blob/main/SimpleUnitTests/Rhino.Testing.Configs.xml) as following

```xml
<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <RhinoSystemDirectory>/Applications/Rhino 8.app/Contents/</RhinoSystemDirectory>
  <LoadGrasshopper>true</LoadGrasshopper>
</Settings>

```

I can run `dotnet build` successfully.  However, `dotnet test` will raise errors like 

```sh
...

Failed TestOpen [17 ms]
  Error Message:
   OneTimeSetUp: System.IO.FileNotFoundException : Could not load file or assembly 'RhinoCommon, Version=8.6.24101.5001, Culture=neutral, PublicKeyToken=552281e97c755530'. The system cannot find the file specified.

  Stack Trace:
     at Rhino.Testing.RhinoCoreLoader.LoadCore(Boolean createDoc, Boolean createView)
   at Rhino.Testing.RhinoCore.Initialize()
   at Rhino.Testing.Fixtures.RhinoSetupFixture.OneTimeSetup()
   at SimpleNUnitTests.SetupFixture.OneTimeSetup() in /Users/xxxxxxxxx/test/SimpleRhinoTests/SimpleUnitTests/SetupFixture.cs:line 12
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

...
```

## Environment

Operating System: macOS 14
Rhino Version: Version 8  (8.7.24138.15432)
Development Environment: Visual Studio, .Net 7.0

**Comment by fraguada** [comment]
This is not yet working on macOS

**Comment by eirannejad** [comment]
Rhino.Testing does not support macOS yet but we are working on it. Closing this ticket.
